import enum


class SpellTypes(enum.IntFlag):
    INVALID = -1
    BUFF = 1
    EVOCATION = 2
    RITUAL = 4
    ALLOW_BATTLEFIELD = 8
    POWER_SCALES_NREFF = 16
    POWER_SCALES_AOE = 32
    POWER_SCALES_DAMAGE = 64
    POWER_SCALES_MAXBOUNCES = 128
    POWER_SCALES_EFFECTNO = 256
    BATTLESUMMON = 512
    ALLOW_NO_SLAVE_COST = 1024
    BATTLE_ENCHANT = 2048